#!/bin/bash
# Usage guide for the Data Analysis Project

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║         Data Analysis Project - Complete Usage Guide            ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""

echo "📊 PROJECT OVERVIEW"
echo "────────────────────────────────────────────────────────────────────"
echo "This tool analyzes datasets in multiple formats (CSV, JSON, Excel)"
echo "and generates professional DOCX reports with comprehensive analysis."
echo ""

echo "✅ SUPPORTED DATA FORMATS"
echo "────────────────────────────────────────────────────────────────────"
echo "  • CSV (Comma-Separated Values)"
echo "  • JSON (JavaScript Object Notation)"
echo "  • XLSX (Excel 2007+)"
echo "  • XLS (Excel 97-2003)"
echo "  • TSV (Tab-Separated Values)"
echo "  • TXT (Text files)"
echo ""

echo "🚀 QUICK START"
echo "────────────────────────────────────────────────────────────────────"
echo ""
echo "1. Navigate to project:"
echo "   cd /home/Unthinkable/Documents/Data-analysis-Project"
echo ""
echo "2. Activate virtual environment:"
echo "   source venv/bin/activate"
echo ""
echo "3. Run analysis:"
echo "   python main.py your_data.csv your_report.docx"
echo ""
echo "4. Open the generated DOCX file with Word, Google Docs, or LibreOffice"
echo ""

echo "📋 ANALYSIS FEATURES"
echo "────────────────────────────────────────────────────────────────────"
echo "✓ Data Overview (rows, columns, data types, memory usage)"
echo "✓ Missing Data Analysis (detection and visualization)"
echo "✓ Statistical Analysis (mean, median, std dev, quartiles, skewness)"
echo "✓ Distribution Analysis (normality tests, distribution types)"
echo "✓ Categorical Analysis (unique values, top values, distributions)"
echo "✓ Outlier Detection (IQR-based outliers and percentages)"
echo "✓ Class Balance Analysis (imbalance ratios and class distribution)"
echo "✓ Correlation Analysis (strong correlations between variables)"
echo "✓ Professional Visualizations (histograms, box plots, heatmaps)"
echo ""

echo "📝 EXAMPLE COMMANDS"
echo "────────────────────────────────────────────────────────────────────"
echo ""
echo "Analyze CSV data:"
echo "  python main.py sample_data.csv report.docx"
echo ""
echo "Analyze JSON data:"
echo "  python main.py sample_employee_data.json employee_report.docx"
echo ""
echo "Analyze Excel data:"
echo "  python main.py sample_website_data.xlsx website_report.docx"
echo ""
echo "Use default output filename (data_analysis_report.docx):"
echo "  python main.py your_data.csv"
echo ""

echo "🔍 REPORT CONTENTS"
echo "────────────────────────────────────────────────────────────────────"
echo "1. Title Page & Table of Contents"
echo "2. Executive Summary - High-level dataset statistics"
echo "3. Data Overview - Column names and data types"
echo "4. Missing Data Analysis - Missing value patterns with charts"
echo "5. Numeric Statistics - Detailed stats for numeric columns"
echo "6. Distribution Analysis - Normality and distribution types"
echo "7. Categorical Analysis - Value distributions"
echo "8. Outlier Detection - Outlier counts and percentages"
echo "9. Class Balance Analysis - For classification problems"
echo "10. Correlation Analysis - Relationships between variables"
echo "11. Visualizations - Charts, histograms, heatmaps"
echo ""

echo "🎯 INTERPRETING YOUR REPORT"
echo "────────────────────────────────────────────────────────────────────"
echo ""
echo "Missing Data (look for >20% - might indicate data quality issues):"
echo "  Check the 'Missing Data Analysis' section"
echo "  Decide: imputation, deletion, or special handling"
echo ""
echo "Distribution (is data normal or skewed?):"
echo "  Check 'Distribution Analysis' section"
echo "  Action: Transform skewed data using log or power transformation"
echo ""
echo "Outliers (unusual values that stand out):"
echo "  Check 'Outlier Detection' section"
echo "  Action: Investigate causes or decide on removal/transformation"
echo ""
echo "Class Balance (important for classification):"
echo "  Check 'Class Balance Analysis' section"
echo "  Action: Use techniques like SMOTE if highly imbalanced (ratio >3)"
echo ""
echo "Correlations (which variables are related?):"
echo "  Check 'Correlation Analysis' section"
echo "  Action: Remove highly correlated features (>0.9) to avoid multicollinearity"
echo ""

echo "💡 COMMON USE CASES"
echo "────────────────────────────────────────────────────────────────────"
echo ""
echo "Use Case 1: Pre-ML Data Exploration"
echo "  python main.py dataset.csv eda.docx"
echo "  Review: missing data, outliers, class balance, skewness"
echo ""
echo "Use Case 2: Data Quality Assessment"
echo "  python main.py raw_data.csv quality_check.docx"
echo "  Review: duplicates, missing values, data type consistency"
echo ""
echo "Use Case 3: Feature Engineering"
echo "  python main.py features.csv feature_analysis.docx"
echo "  Review: correlations, skewness, distributions"
echo ""
echo "Use Case 4: Business Intelligence"
echo "  python main.py sales_data.csv sales_analysis.docx"
echo "  Review: trends, distributions, outliers"
echo ""

echo "⚙️  CUSTOMIZING THE TOOL"
echo "────────────────────────────────────────────────────────────────────"
echo ""
echo "Edit analysis parameters in data_analyzer.py:"
echo "  • Outlier sensitivity (IQR multiplier)"
echo "  • Class balance threshold"
echo "  • Normality significance level"
echo ""
echo "Add custom visualizations in report_generator.py:"
echo "  • Time series plots"
echo "  • Scatter plots"
echo "  • Custom charts"
echo ""

echo "🔧 TROUBLESHOOTING"
echo "────────────────────────────────────────────────────────────────────"
echo ""
echo "Issue: 'module not found' error"
echo "  Solution: Activate virtual environment"
echo "  Run: source venv/bin/activate"
echo ""
echo "Issue: 'file not found' error"
echo "  Solution: Check file path and ensure file exists"
echo "  Use: ls -la your_file.csv"
echo ""
echo "Issue: 'Unsupported format' error"
echo "  Solution: Ensure file is in supported format"
echo "  Supported: CSV, JSON, XLSX, XLS, TSV, TXT"
echo ""
echo "Issue: Analysis taking long time"
echo "  Solution: Normal for large files (>50MB)"
echo "  Typical times: <1MB = 5-10s, 1-50MB = 15-30s, >50MB = 1-2min"
echo ""

echo "📊 UNDERSTANDING KEY METRICS"
echo "────────────────────────────────────────────────────────────────────"
echo ""
echo "Skewness (measure of asymmetry):"
echo "  -0.5 to 0.5  → Fairly symmetric (good)"
echo "  0.5 to 1     → Moderately right-skewed"
echo "  > 1          → Highly right-skewed (consider log transform)"
echo "  < -1         → Highly left-skewed (consider log transform)"
echo ""
echo "Coefficient of Variation (relative variability):"
echo "  < 15%  → Low variability (consistent data)"
echo "  15-30% → Moderate variability"
echo "  > 30%  → High variability (diverse data)"
echo ""
echo "Imbalance Ratio (for classification):"
echo "  1.0      → Perfect balance"
echo "  1-3      → Well balanced"
echo "  3-10     → Moderately imbalanced"
echo "  > 10     → Highly imbalanced (needs special handling)"
echo ""
echo "Correlation (relationship strength):"
echo "  0.0-0.3  → Weak"
echo "  0.3-0.7  → Moderate"
echo "  0.7-1.0  → Strong"
echo "  1.0      → Perfect (same variable)"
echo ""

echo "✨ NEXT STEPS AFTER ANALYSIS"
echo "────────────────────────────────────────────────────────────────────"
echo "1. Read and understand the generated report"
echo "2. Identify data quality issues"
echo "3. Plan data cleaning strategy"
echo "4. Handle missing values (imputation/removal)"
echo "5. Treat outliers (transformation/removal)"
echo "6. Balance classes if needed (SMOTE/undersampling)"
echo "7. Transform skewed variables"
echo "8. Scale numeric features"
echo "9. Encode categorical variables"
echo "10. Build your predictive model"
echo ""

echo "📚 FOR MORE INFORMATION"
echo "────────────────────────────────────────────────────────────────────"
echo "Read: README.md - Complete documentation"
echo "Read: QUICKSTART.md - Beginner-friendly guide"
echo "Check: Code comments in Python files"
echo ""

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                     Happy Analyzing! 📊✨                        ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
